---
-
    name: meter_pipeline
    interval: 100
    meters:
        - "*"
    transformers:
    publishers:
        - rpc://
-
    name: cpu_pipeline
    interval: 100
    meters:
        - "cpu"
    transformers:
        - name: "rate_of_change"
          parameters:
              target:
                  name: "cpu_util"
                  unit: "%"
                  type: "gauge"
                  scale: "100.0 / (10**9 * (resource_metadata.cpu_number or 1))"
    publishers:
        - rpc://
-
    name: uptime_pipeline
    interval: 100
    meters:
        - "state"
    transformers:
        - name: "uptime"
          parameters:
              target:
                  name: "uptime"
                  unit: "second"
                  type: "cumulative"
                  active: [1, 2, 3, 6, 7]
    publishers:
        - rpc://